PagerDuty API requires HTTPS.
Updated all PD API calls to use HTTPS to avoid redirect HTML from breaking JSON parsing:

$ node bot.js
undefined:1
<html><body>You are being <a href="https://acme.pagerduty.com/api/v1/servic
^
SyntaxError: Unexpected token <

Tested this fix as working.